# -*- coding: utf-8 -*-
"""Senai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgO2mBZeh8FTrAmVjoi3jVuhgbfchADc
"""

import math
num = float(input("Entre com um número:\n"))
raiz = math.pow(num, 1/2)
print(f'\nA raiz quadrada de {num} é {raiz}\n')

num=1
count=20
if num <=count:
  num=num+1
  for num in range (count):
    print (num)

num=int(input("Digite um numero: "))
print("A Tabuda do ")
for i in range (10):
  print("%d x %d = %d" % (num, i+1, num*(i+1)))

numero_1 = 2
numero_2 = 4

soma = numero_1 + numero_2

if soma < 10:
  print("Soma não é maior que 10")
else:
  print("Soma é maior que 10")

#Aula

idade_lucas=18
idade_carolina = 18

#Uso do OR
if idade_lucas >= 18 or idade_carolina >= 18:
  print("Pelo menos um dos dois é maior de idade.")

else:
  print("Lucas e Carolina não são maiores de idade")

#Uso do AND

if idade_lucas >= 18 == idade_carolina >= 18:
  print("Lucas e Carolina são maiores de idade.")

else:
  print("Pelo menos um dos dois é maior de idade.")

#Com input
idade_lucas=int(input("Qual é a idade de Lucas?"))
idade_carolina = int(input("Qual é a idade de Carolina?"))

#Uso do OR
if idade_lucas >= 18 or idade_carolina >= 18:
  print("Pelo menos um dos dois é maior de idade.")

  if idade_carolina <=80:
    print("VELHA")


else:
  print("Lucas e Carolina não são maiores de idade")

#Uso do AND

i#f idade_lucas >= 18 and idade_carolina >= 18:
  #print("Lucas e Carolina são maiores de idade.")

#elif idade_lucas >= 18 and idade_carolina >= 18:
    #print("Pelo menos um dos dois é maior de idade.")

#else:
  #print("Lucas e Carolina não são maiores de idade")

banda = input('Qual melhor banda do mundo? ')

if not banda=='rush':
    print('Herege!')
else:
    print('Correto, é o Rush!')

num_1=int(input("Digite o primeiro numero: "))
num_2=int(input("Digite o segundo numero: "))

total=num_1 + num_2
print("O valor da soma é ",num_1+num_2)
print ("O valor da soma é ",total)
print("O valor da soma é %d"%(total))
print ("O valor da soma %d + %d = %d "%(num_1,num_2,total))
print(f"o valor {total}","é o resultado da soma %d + %d"%(num_1,num_2))

n = int(input("Verificar numeros primos ate: "))
mult=0

for count in range(2,n):
    if (n % count == 0):
        print("Múltiplo de",count)
        mult += 1

if(mult==0):
    print("É primo")
else:
    print("Tem",mult," múltiplos acima de 2 e abaixo de",n)